FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt .
COPY requirements-dashboard.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=200 --retries=10 -r requirements-dashboard.txt


# Copie le contenu du dossier app local vers /app dans le container
COPY app/ .

EXPOSE 8501
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]